# Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy.


In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
arr1 = np.array((1,2,3,4))
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [10]:
arr2 = np.array((1,2,3,4,5))
arr2.reshape(1,5)
arr2.shape
type(arr2)

numpy.ndarray

In [16]:
arr3 = np.arange(0,20,2).reshape(2,5)
print(arr3)
print(type(arr3))
print(arr3.shape)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
<class 'numpy.ndarray'>
(2, 5)


In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# identity elements
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#  Attributes of numpy array
#  ---------------------------
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array: ", arr)
print("Sahpe: ", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size : " ,arr.size)
print("Data Type: ",arr.size)
print("Item Size: ", arr.itemsize)

Array:  [[1 2 3 4]
 [5 6 7 8]]
Sahpe:  (2, 4)
Number of Dimensions:  2
Size :  8
Data Type:  8
Item Size:  4


In [27]:
# Numpy Vectorized Operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print("Addition: ", arr1 + arr2 )
print("Subtraction: ", arr1 - arr2 )
print("Division: ", arr1 / arr2 )
print("Multiplication: ", arr1 * arr2 )


Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Division:  [0.1 0.1 0.1 0.1 0.1]
Multiplication:  [ 10  40  90 160 250]


In [28]:
arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [30]:
# Universal Functions
# Array Slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [32]:
arr[0][1]

2

In [36]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [38]:
arr[0:,0:]
arr[0:,3:]

array([[ 4],
       [ 8],
       [12]])

In [39]:
# Statisticaal concepts --normalization
data = np.array([1,2,3,4,5])
print(np.mean(data)) # mean
print(np.std(data)) # standard daviation




3.0
1.4142135623730951
